//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaugeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> Importance__in______International_events { get; set; }
        public Nullable<int> Importance__in______National_events { get; set; }
        public string Criteria { get; set; }
        public string Indicators { get; set; }
        public string Source { get; set; }
        public int Weight { get; set; }
        public string Question { get; set; }
        public string Answers { get; set; }
        public int Score { get; set; }
        public Nullable<int> Selected_score { get; set; }
        public Nullable<int> Average_score { get; set; }
        public Nullable<int> Score_per_indicator { get; set; }
        public Nullable<int> Average_score_per_criteria { get; set; }
        public Nullable<int> Final_score_per_indicator___international_events { get; set; }
        public Nullable<int> Final_score_per_indicator___national_events { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
