//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaugeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public int EntityID { get; set; }
        public string Entity_Name { get; set; }
        public string Entity_address { get; set; }
        public string Entity_Telephone_Number { get; set; }
        public string Entity_P_O_Box_Number { get; set; }
        public string Entity_Fax_Number { get; set; }
        public string Entity_Website { get; set; }
        public string Entity_Email { get; set; }
        public string CEO__President_Name { get; set; }
        public string E_mail_Address { get; set; }
        public string Managing_Director_Name { get; set; }
        public string E_mail_Address_Director { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
