//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaugeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string Criteria { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Venue { get; set; }
        public string Source { get; set; }
        public int Weight { get; set; }
        public string Budget { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public string Frequency { get; set; }
        public string Estimated_Number_of_Participants { get; set; }
        public string Estimated_Number_of_Attendees { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
