//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaugeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string EventCriteria { get; set; }
        public Nullable<System.DateTime> EventStartDate { get; set; }
        public Nullable<System.DateTime> EventEndDate { get; set; }
        public string EventDescription { get; set; }
        public string EventVenue { get; set; }
        public string EventSource { get; set; }
        public Nullable<int> Weight { get; set; }
        public string EventBudget { get; set; }
        public string EventCategory { get; set; }
        public string EventType { get; set; }
        public string EventFrequency { get; set; }
        public string EventCordinatorName { get; set; }
        public string EventCordinatorMobileNumber { get; set; }
        public string EventCordinatorEmail { get; set; }
        public string Estimated_Number_of_Participants { get; set; }
        public string Estimated_Number_of_Attendees { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
