//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaugeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int SchoolID { get; set; }
        public string School_University_Name { get; set; }
        public string Institution_Address { get; set; }
        public string Telephone_Number { get; set; }
        public string Institution_P_O_Box_Number { get; set; }
        public string Institution_Fax_Number { get; set; }
        public string Institution_Website { get; set; }
        public string Principal_Dean_Name { get; set; }
        public string Principal_Dean_Email { get; set; }
        public string Principal_Dean_Passport_Copy { get; set; }
        public string Event_Coordinator_Name { get; set; }
        public string Event_Coordinator_Mobile_Number { get; set; }
        public string Event_Coordinator_Passport_Copy { get; set; }
        public int CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
